//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employer_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employer_details()
        {
            this.Vacancy_details = new HashSet<Vacancy_details>();
        }
    
        public int id { get; set; }
        public string Company_name { get; set; }
        public string Company_background { get; set; }
        public string Company_locatiion { get; set; }
        public string Campany_contact_number { get; set; }
        public Nullable<int> Workforce_number { get; set; }
        public string Company_Email { get; set; }
        public string Industry_type { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vacancy_details> Vacancy_details { get; set; }
    }
}
