//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employer_details
    {
        public int id { get; set; }
        public string Company_name { get; set; }
        public string Company_background { get; set; }
        public string Company_locatiion { get; set; }
        public string Campany_contact_number { get; set; }
        public Nullable<int> Workforce_number { get; set; }
        public Nullable<int> Vacancy_id { get; set; }
        public string Company_Email { get; set; }
        public string Industry_type { get; set; }
        public string Password { get; set; }
    
        public virtual Vacancy_details Vacancy_details { get; set; }
    }
}
