//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job_Applications_details
    {
        public int id { get; set; }
        public Nullable<int> resume_id { get; set; }
        public Nullable<int> Jobseeker_id { get; set; }
        public Nullable<int> vacancy_id { get; set; }
        public Nullable<bool> Application_status { get; set; }
    
        public virtual Vacancy_details Vacancy_details { get; set; }
        public virtual Jobseeker_details Jobseeker_details { get; set; }
        public virtual Resume_details Resume_details { get; set; }
    }
}
