//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resume_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Resume_details()
        {
            this.Job_Applications_details = new HashSet<Job_Applications_details>();
            this.Jobseeker_details = new HashSet<Jobseeker_details>();
        }
    
        public int id { get; set; }
        public string Education_level { get; set; }
        public string Qualifications { get; set; }
        public string PriorWork_Experiences { get; set; }
        public string Hobbies { get; set; }
        public string Contact_number { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Job_Applications_details> Job_Applications_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Jobseeker_details> Jobseeker_details { get; set; }
    }
}
