//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacancy_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vacancy_details()
        {
            this.Job_Applications_details = new HashSet<Job_Applications_details>();
        }
    
        public int id { get; set; }
        public string Job_title { get; set; }
        public string Job_Discription { get; set; }
        public string Job_Requirements { get; set; }
        public string Job_level { get; set; }
        public string Employment_type { get; set; }
        public Nullable<System.DateTime> Submit_deadline { get; set; }
        public string Job_category { get; set; }
        public Nullable<int> Employers_id { get; set; }
    
        public virtual Employer_details Employer_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Job_Applications_details> Job_Applications_details { get; set; }
    }
}
