//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rental_records
    {
        public int id { get; set; }
        public System.DateTime rent_date { get; set; }
        public System.DateTime return_date { get; set; }
        public string customer_name { get; set; }
        public decimal cost { get; set; }
        public int type_of_car_id { get; set; }
    
        public virtual Type_of_car Type_of_car { get; set; }
    }
}
